### ISSUE TITLE
Reporte Práctica 1

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/practica-architect-IsraelNicolas61#1]
[Reporte practica 1.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-IsraelNicolas61/files/7171864/Reporte.practica.1.pdf)

**Comment by DuilioAquino10** [comment]
Calificación: 19.4 
Califico: Duilio Ruben Aquino López.

**Comment by DuilioAquino10** [comment]
Calificación 18
Califico Duilio Ruben Aquino López.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado..
